service: upschool-sendMail-${opt:stage}-sendMail
provider:
  name: aws
  runtime: nodejs20.x
  lambdaHashingVersion: '20201221'
  region: ap-south-1
  stage: ${opt:stage}
  environment:    
    NODE_ENV: ${self:provider.stage}
    SENDER_EMAIL: ${file(config/${self:provider.stage}-config.yml):data.sendGrid.senderEmail}
    SENDGRID_API_KEY: ${file(config/${self:provider.stage}-config.yml):data.sendGrid.apiKey}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:CreateTable
          Resource:
            - "*"
functions:
  upschool-send-mail:
    name: upschool-sendMail-${opt:stage}-sendMail
    handler: sendMail.handler
    events:
      - sns: ${file(config/${self:provider.stage}-config.yml):data.subscribedTopic.topicArn}


      
