data:
  sendGrid:
    senderEmail:
      - shilpa.rajashekar@rhibhus.com
    apiKey:
      - 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
  subscribedTopic:
    topicArn:
      - arn:aws:sns:ap-south-1:036801103583:${self:provider.stage}-upschool-sendOTP