data:
  sendGrid:
    senderEmail:
      - shilpa.rajashekar@rhibhus.com
    apiKey:
      - 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
  subscribedTopic:
    topicArn:
      - arn:aws:sns:ap-south-1:036801103583:${self:provider.stage}-upschool-sendOTP