data:
  sendGrid:
    senderEmail:
      - sathish.mariappa@rhibhus.com
    apiKey:
      - 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
  subscribedTopic:
    topicArn:
      - arn:aws:sns:ap-south-1:036801103583:${self:provider.stage}-upschool-sendOTP
